spin_manifest_version = 2

[application]
name = "golab"
version = "0.1.0"
authors = ["Daniel Esteban <conejo@theninjabunny.com>"]
description = "My first app"

[[trigger.http]]
route = "/..."
component = "golab"

[component.golab]
source = "main.wasm"
key_value_stores = ["default"]
allowed_outbound_hosts = []
[component.golab.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm ."
watch = ["**/*.go", "go.mod"]
